version: "2"

services:
  remark:
    build: remark
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: remark42
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
     - "8080:8080"

    environment:
      - REMARK_URL=http://localhost:8080
      - SECRET=12345
      - DEBUG=true
      - SITE=remark
      - AUTH_ANON=false
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      # Config server email
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=465
      - SMTP_TLS=true
      - SMTP_USERNAME=apikey
      - SMTP_PASSWORD=####
      # Config auth with email
      - AUTH_EMAIL_SUBJ=remark42 confirmation
      - AUTH_EMAIL_CONTENT_TYPE=text/html
      - AUTH_EMAIL_ENABLE=true
      - AUTH_EMAIL_FROM=xuanthangnguyen2002@gmail.com
    volumes:
      - ./var:/srv/var

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabasedb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metadb
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      
  metabase-pg:
    image: postgres:latest
    container_name: postgres-1
    hostname: metadb
    environment:
      POSTGRES_DB: metabasedb
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    networks:
      - metanet1
    volumes:
    - ./postgres-metabase/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres:
    image: postgres:latest
    container_name: postgres-2
    hostname: webdb
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: bankadmin
      POSTGRES_PASSWORD: admin
    networks:
      - metanet1
    volumes:
    - ./postgres-web/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
networks:
  metanet1:
    driver: bridge