version: "3"

services:
  hsbanking-api:
    # build:
    #   context: backend
    #   dockerfile: Dockerfile
    image: thanhdxuan/hsbanking.com
    container_name: hsbanking
    depends_on:
      - postgres
    hostname: hsbanking
    ports:
     - "5000:8000"
    environment:
    - FLASK_ENV=development
    - FLASK_APP=flask_run.py
    - DEBUG=True
    - FLASK_DEBUG=1
    - LOAN_DASHBOARD_ID=7
    - MARKETING_DASHBOARD=8
    - CREDITCARD_DASHBOARD=5
    - REACT_APP_REMARK_URL=http://remark42:8080
    - REACT_APP_REMARK_SITE_ID=remark
    # Model dirs
    - HTML_BUILD_DIR=html
    - ANALYSIS_DIR=analysis
    - SQLALCHEMY_DATABASE_URI_LOCAL=postgresql://bankadmin:admin@webdb:5432/banking
    - POSTGRE_HOST=webdb
    - POSTGRE_USER=bankadmin
    - POSTGRE_PASSWORD=admin
    - POSTGRE_DB=banking

    - METABASE_SITE_URL=http://localhost:3002
    - METABASE_SECRET_KEY=f3eb3529dfb6ff9578f0b7b747d3776d0efcbb019ee84b7d00ef6528c7bf7a94
    - BANK_MAINTAINER_REMARK_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZW1hcmsiLCJleHAiOjE3MTQzNjQ3NzIsImlzcyI6InJlbWFyazQyIiwibmJmIjoxNzE0MzYyOTEyLCJoYW5kc2hha2UiOnsiaWQiOiJUaGFuaDo6dGhhbmguZGF1eHVhbjI0MDJAaGNtdXQuZWR1LnZuIn19.ye_jmlNzKbvqqUimc3VvOwThkP4Aa2nuWxkaHC88QDo
    # Mail settings
    - SENDGRID_API_KEY=''
    - MAIL_SERVER=smtp.sendgrid.net
    - MAIL_PORT=587
    - MAIL_USE_TLS=True

    - MAIL_USERNAME=apikey
    - MAIL_PASSWORD=''
    - MAIL_DEFAULT_SENDER=thanh.dauxuan2402@hcmut.edu.vn
    networks:
      - metanet1

  remark:
    build: remark
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: remark42
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
     - "8080:8080"

    environment:
      - REMARK_URL=http://localhost:8080
      - SECRET=12345
      - DEBUG=true
      - SITE=remark
      - AUTH_ANON=false
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      # Config server email
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=465
      - SMTP_TLS=true
      - SMTP_USERNAME=apikey
      - SMTP_PASSWORD=####
      # Config auth with email
      - AUTH_EMAIL_SUBJ=remark42 confirmation
      - AUTH_EMAIL_CONTENT_TYPE=text/html
      - AUTH_EMAIL_ENABLE=true
      - AUTH_EMAIL_FROM=xuanthangnguyen2002@gmail.com
    volumes:
      - ./var:/srv/var

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabasedb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metadb
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase-pg:
    image: postgres:latest
    container_name: postgres-metabase
    hostname: metadb
    environment:
      POSTGRES_DB: metabasedb
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    networks:
      - metanet1
    volumes:
    - ./postgres-metabase/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres:
    # build:
    #   context: db
    #   dockerfile: Dockerfile
    image: bank-mining-postgres
    container_name: postgres-web
    hostname: webdb
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: bankadmin
      POSTGRES_PASSWORD: admin
    networks:
      - metanet1
    volumes:
    - ./postgres-web/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
networks:
  metanet1:
    driver: bridge
