const listLoanParams = [
  ['customer_id', 'ID of customer who submitted this application.', 'normal', 'Customer ID'],
  [
    'credit_policy',
    '1 if the customer meets the credit underwriting criteria; 0 otherwise.',
    'select',
    ['yes', 'no'],
    [1, 0],
    'Credit Policy',
  ],
  [
    'purpose',
    'The purpose of the loan.',
    'select',
    [
      'Debt Consolidation',
      'Educational',
      'Credit Card',
      'Major Purchase',
      'Home Improvement',
      'Small Business',
      'Other',
    ],
    [
      'debt_consolidation',
      'educational',
      'credit_card',
      'major_purchase',
      'home_improvement',
      'small_business',
      'all_other',
    ],
    'Purpose',
  ],
  [
    'int_rate',
    'The interest rate of the loan (more risky borrowers are assigned higher interest rates).',
    'normal',
    'Interest Rate (%)',
  ],
  [
    'installment',
    'The monthly installments owed by the borrower if the loan is funded.',
    'normal',
    'Installment ($)',
  ],
  [
    'log_annual_inc',
    'The natural log of the self-reported annual income of the borrower.',
    'normal',
    'Annualy Income ($)',
  ],
  [
    'dti',
    'The debt-to-income ratio of the borrower (amount of debt divided by annual income).',
    'normal',
  ],
  ['fico', 'The FICO credit score of the borrower.', 'normal', 'Credit Score'],
  [
    'days_with_cr_line',
    'The number of days the borrower has had a credit line.',
    'normal',
    'Day With Credit Line',
  ],
  [
    'revol_bal',
    "The borrower's revolving balance (amount unpaid at the end of the credit card billing cycle).",
    'normal',
    'Revoling Balance',
  ],
  [
    'revol_util',
    "The borrower's revolving line utilization rate (the amount of the credit line used relative to total credit available).",
    'normal',
    'Revolving Utilization',
  ],
  [
    'inq_last_6mths',
    "The borrower's number of inquiries by creditors in the last 6 months.",
    'select',
    ['yes', 'no'],
    [1, 0],
    'Inquiries Last 6mths',
  ],
  [
    'delinq_2yrs',
    'The number of times the borrower had been 30+ days past due on a payment in the past 2 years.',
    'select',
    ['yes', 'no'],
    [1, 0],
    'Delinquent 2 years',
  ],
  [
    'pub_rec',
    "The borrower's number of derogatory public records.",
    'select',
    ['yes', 'no'],
    [1, 0],
    'Bad Public Record',
  ],
]

export default listLoanParams
